version: '3.9'

services:
  my-news-service-01-dev:
    image: ${CONTAINER_REGISTRY_URL}/${CONTAINER_IMAGE_REPOSITORY}:${CONTAINER_IMAGE_TAG}

    ports:
      - ${HOST_PORT_PREFIX}55:5555
    volumes:
      - ${HOST_MSR_LICENSE_FILE}:${GUEST_LIC_MOUNT_POINT}
      - ./application.properties:${GUEST_APP_PROPS_MOUNT_POINT}
      - ../../:/mnt/project-home/
      - ./local/:/mnt/local/
      - ./scripts/:/mnt/scripts/
      - ../../code/is-packages/MyNewsService/:${GUEST_IS_HOME}/packages/MyNewsService/
      - ../../code/is-packages/MyMailService/:${GUEST_IS_HOME}/packages/MyMailService/
    environment:
      - SAG_IS_LICENSE_FILE=${GUEST_LIC_MOUNT_POINT}
      - SAG_IS_CONFIG_PROPERTIES=${GUEST_APP_PROPS_MOUNT_POINT}
      - LOCAL_PRODUCE_DUMPS=1
      # SMTP configuration
      - SMTP_HOST_NAME
      - SMTP_HOST_PORT
      - SMTP_USER_EMAIL
      - SMTP_USER_PASS
      # NEWS API configuration
      - NEWSAPI_BASE_URL
      - NEWSAPI_API_KEY
    # entrypoint: /mnt/scripts/entrypoint.sh
