version: '3.9'

services:
  my-news-service-01-dev:
    image: mi24a7acr.azurecr.io/msr-1015-lean-original-recipe:Fixes_24-02-12
    ports:
      - ${HOST_PORT_PREFIX}55:5555
    volumes:
      - ${HOST_MSR_LICENSE_FILE}:/tmp/license.xml
    environment:
      - SAG_IS_LICENSE_FILE=/tmp/license.xml